# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://beginman.cn
date_format: "ordinal"
title: Beginman
subtitle: "ğŸ˜è™šå¿ƒè°¦å‘ï¼Œæ°¸è¿œåšä¸ªå°å­¦ç”Ÿï¼"
description: "beginman's blog"
keywords: beginman, åšå®¢, å­¦ä¹ , æ€»ç»“
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Beginman
organization: None, Inc.
organization_url: https://www.google.com
location: Beijing, China
email: pythonsuper@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: é¦–é¡µ

  -
    href: /categories/
    label: åˆ†ç±»

  -
    href: /wiki/
    label: ç»´åŸº

  -
    href: /links/
    label: é“¾æ¥

  -
    href: /about/
    label: å…³äº

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: beginman/beginman.github.io

# ---------------- #
#      Socials     #
# ---------------- #
github_username: beginman
#douban_username: beginman
#facebook_username: beginman
#weibo_username: beginman
#zhihu_username: beginman
#twitter_username: fpsir

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: disqus
# !!!é‡è¦!!! è¯·ä¿®æ”¹ä¸‹é¢ä¸¤ä¸ªç”¨æˆ·åä¸ºä½ è‡ªå·±ç”³è¯·çš„
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: beginman
disqus_username: beginman
# åœ¨ä½¿ç”¨ disqus çš„æ—¶å€™å¯ç‚¹å‡»æ˜¾ç¤ºå¤šè¯´è¯„è®ºæ¡†
lazy_load_duoshuo: true

# ---------------- #
#    Analytics     #
# ---------------- #
#google:
#    analytics_id: UA-80669434-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Python, JS]
